### PR TITLE
[Jenkins] balance and fix cleanup of toku job

### PR DESCRIPTION
**Pull request by msagarpatel**
Manually import toku job cleanup changes from internal repo to prevent
lingering VM images.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/21)

### CODE REVIEW

**Comment by donporter** [comment]
Add to whitelist

**Review by donporter — DISMISSED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/21)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by msagarpatel** [comment]
Retest toku please. I aborted the pervious job.

**Comment by msagarpatel** [comment]
Jenkins, retest toku please

**Comment by msagarpatel** [comment]
Retest this please

**Comment by msagarpatel** [comment]
Retest toku please. Should trigger the job this time.

**Comment by msagarpatel** [comment]
Retest toku please. Might need to add a `sleep 30` or `vagrant status` before `vagrant ssh`, but let's try without that one more time.
```
+ cd Jenkinsfiles/test4
+ vagrant ssh -c /bin/dmesg
The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.
```

**Comment by msagarpatel** [comment]
Retest this please

**Comment by msagarpatel** [comment]
Retest this please.

**Comment by msagarpatel** [comment]
Retest toku please

**Comment by msagarpatel** [comment]
Retest toke please

**Comment by msagarpatel** [comment]
Retest toku please

**Comment by msagarpatel** [comment]
Retest toku please

**Comment by msagarpatel** [comment]
Retest toku please. The last job just started running, but I want to force this job to run on a particular node.

**Comment by msagarpatel** [comment]
Retest this please

**Comment by msagarpatel** [comment]
For the record, benchmarks and toku both passed before the previous revert commit. However, it's possible that there was only one executor per node then.

**Comment by msagarpatel** [comment]
Retest this please. benchmarks passed, and toku failed.

**Comment by msagarpatel** [comment]
Retest this please. Both toku and benchmarks passed.

**Comment by msagarpatel** [comment]
Retest this please. Passed toku and benchmarks once.

**Review by donporter — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r3, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/21)* status: all files reviewed, 2 unresolved discussions (waiting on @msagarpatel)

___
*[Jenkinsfiles/Linux, line 37 at r6](https://reviewable.io/reviews/oscarlab/betrfs/21#-MUAwY4iBBYuPQEwkmtt:-MUAwY4iBBYuPQEwkmtu:b-1sdj12) ([raw file](https://github.com/oscarlab/betrfs/blob/3979573ff0a0f5b243b490b133e79401f9693896/Jenkinsfiles/Linux#L37)):*
> ```
>                 sh '''
>                 cd Jenkinsfiles/test1
>                 # comment this out since it's causing problems
> ```

Can you expand this comment slightly, like just to explain that it is an intermittent failure that causes the job to fail, but the job actually succeeded - we only lost the debugging info.  Think about a newbie in like 2 years trying to figure out how to get dmesg and where to pick up where you left off.

I also mentioned that maybe just not setting result is enough, or perhaps some other try/catch syntax here.  Don't spend much time; we can just live with this too.
___
*[Jenkinsfiles/Linux-benchmarks, line 40 at r6](https://reviewable.io/reviews/oscarlab/betrfs/21#-MUAwRYf77TTDZrsGWcf:-MUAwRYf77TTDZrsGWcg:b-avtbav) ([raw file](https://github.com/oscarlab/betrfs/blob/3979573ff0a0f5b243b490b133e79401f9693896/Jenkinsfiles/Linux-benchmarks#L40)):*
> ```
>       sh '''
>       cd Jenkinsfiles
>       vagrant status
> ```

Do we still need this in the final merge?

**Review by msagarpatel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/21)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @donporter)

___
*[Jenkinsfiles/Linux, line 37 at r6](https://reviewable.io/reviews/oscarlab/betrfs/21#-MUAwY4iBBYuPQEwkmtt:-MUC2oE74YkkYSvDzaqk:bq1ipuo) ([raw file](https://github.com/oscarlab/betrfs/blob/3979573ff0a0f5b243b490b133e79401f9693896/Jenkinsfiles/Linux#L37)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Can you expand this comment slightly, like just to explain that it is an intermittent failure that causes the job to fail, but the job actually succeeded - we only lost the debugging info.  Think about a newbie in like 2 years trying to figure out how to get dmesg and where to pick up where you left off.

I also mentioned that maybe just not setting result is enough, or perhaps some other try/catch syntax here.  Don't spend much time; we can just live with this too.
</blockquote></details>

try-catch ended up working. [Here](https://leeroy2.cs.unc.edu:8082/job/betrfs/212/flowGraphTable/) is a job that failed to print dmesg, and the catch block still destroyed the VM.
___
*[Jenkinsfiles/Linux-benchmarks, line 40 at r6](https://reviewable.io/reviews/oscarlab/betrfs/21#-MUAwRYf77TTDZrsGWcf:-MUC3LBi2rb726KO94nv:b9y62a5) ([raw file](https://github.com/oscarlab/betrfs/blob/3979573ff0a0f5b243b490b133e79401f9693896/Jenkinsfiles/Linux-benchmarks#L40)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Do we still need this in the final merge?
</blockquote></details>

The `vagrant status` isn't needed, but I just left it there in case it ever contains useful information in the future. Should I remove it?

**Review by donporter — APPROVED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/21)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Jenkinsfiles/Linux-benchmarks, line 40 at r6](https://reviewable.io/reviews/oscarlab/betrfs/21#-MUAwRYf77TTDZrsGWcf:-MUEEKbP0tdCUUXaNwzU:bitfnh9) ([raw file](https://github.com/oscarlab/betrfs/blob/3979573ff0a0f5b243b490b133e79401f9693896/Jenkinsfiles/Linux-benchmarks#L40)):*
<details><summary><i>Previously, msagarpatel (Sagar Patel) wrote…</i></summary><blockquote>

The `vagrant status` isn't needed, but I just left it there in case it ever contains useful information in the future. Should I remove it?
</blockquote></details>

I suppose it is fine to leave it.

**Pull request merged**
