### PR TITLE
Import CI code and other utils for Toku jobs from private repo.

### PR DESCRIPTION
**Pull request by donporter**
Just for testing right now.

This is a bulk import of work to adopt CI for Betrfs in our internal repo.  Here, we are focused on just getting the Toku unit tests running on the public repo.

This includes a number of bugfixes.

This also includes code from Yizheng Jiao, David Cowhig, Jun Yuan, and Yang Zhan

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/11)

### CODE REVIEW

**Comment by donporter** [comment]
Ok to test

**Comment by donporter** [comment]
Add to whitelist

**Comment by donporter** [comment]
Retest this please

**Comment by jyuan2pace** [comment]
Retest Toku please

**Comment by jyuan2pace** [comment]
Retest this please

**Comment by jyuan2pace** [comment]
I want to check jenkin logs of how pick child failed. but the log did not go as far as August. I would like to retest it. How do I start a retest? I thought it was "Retest Toku please"?

**Comment by jyuan2pace** [comment]
Retest Toku please.

**Comment by donporter** [comment]
Add to whitelist

**Comment by donporter** [comment]
@Jun-Yuan This Jenkins pipeline doesn't "know" you yet.  Sorry.  Your requests for a retest should work now.

**Comment by donporter** [comment]
I am going to skip the review step, since each of these have been reviewed on the private repo (and we are a bit short-handed on reviewing at the moment).

**Pull request merged**
