### PR TITLE
[In progress] port smt_pivot modification from internal repo 

### PR DESCRIPTION
**Pull request by ericafu1122**
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/19)

### CODE REVIEW

**Comment by ericafu1122** [comment]
retest toku please

**Comment by ericafu1122** [comment]
retest TOKU please

**Comment by donporter** [comment]
Add to whitelist

**Comment by ericafu1122** [comment]
retest Benchmarks please

**Comment by ericafu1122** [comment]
retest Toku please

**Comment by ericafu1122** [comment]
retest toku please

**Comment by ericafu1122** [comment]
retest toku test please

**Comment by ericafu1122** [comment]
retest this please

**Comment by ericafu1122** [comment]
retest this

**Comment by ericafu1122** [comment]
retest this please

**Comment by ericafu1122** [comment]
retest this please

**Comment by ericafu1122** [comment]
retest this please

**Pull request closed without merging**
