### PR TITLE
Enable XFSTESTS

### PR DESCRIPTION
**Pull request by donporter**
Try turning on the XFSTEST jenkins job for this repo.

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/20)

### CODE REVIEW

**Comment by donporter** [comment]
Test XFS please.

**Comment by donporter** [comment]
Test XFS please

**Comment by donporter** [comment]
Retest XFS please

**Comment by donporter** [comment]
Retest XFS please.  File system issue?

**Comment by donporter** [comment]
Retest XFS please.  Out of memory issue in last test.

**Comment by donporter** [comment]
Retests Toku please.  Some dicey stuff on sameagle; maybe also a legit bug...

**Comment by donporter** [comment]
Retest Toku please. Some dicey stuff on sameagle; maybe also a legit bug...  Typo in previous request

**Review by msagarpatel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 5 of 31 files at r2, 3 of 5 files at r3, 9 of 12 files at r4, 1 of 28 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/20)* status: 17 of 19 files reviewed, 8 unresolved discussions (waiting on @donporter)

___
*[benchmarks/clear-fs-caches.sh, line 36 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5tEfk9zKsHUiJ6Hfc:-MW5tEfk9zKsHUiJ6Hfd:b-kka71u) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/benchmarks/clear-fs-caches.sh#L36)):*
> ```Shell
> elif [[ $fstype == "ftfs" ]]
> then
>     if [ -z ${module+x} ]; then echo "module is unset"; exit -1; fi
> ```

Is this necessary? module is defined in fs-info.sh, and that script is sourced by this script.
___
*[filesystem/ftfs_module.c, line 78 at r5](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW6E3VU5ZSrZewnaahM:-MW6E3VVAr6EgnzDCgAr:b-ryw9on) ([raw file](https://github.com/oscarlab/betrfs/blob/fab3824cb1c33eeb7049ba08cbcaba6be16e657d/filesystem/ftfs_module.c#L78)):*
> ```C
> static void __exit ftfs_module_exit(void)
> {
> 	destroy_ft_index();
> ```

Should all of these function declarations and definitions be removed as well?
___
*[Jenkinsfiles/Linux-xfs, line 13 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5ySXy-2bXZ1lH1TpQ:-MW5ySXy-2bXZ1lH1TpR:b-og7w8) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/Jenkinsfiles/Linux-xfs#L13)):*
> ```
>     stage('Testing') {
>       steps {
> 	timeout(time: 75, unit: 'MINUTES') {
> ```

15 minutes should be sufficient.
___
*[Jenkinsfiles/Linux-xfs, line 17 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5yKUW6VOAvBclBO5P:-MW5yKUW6VOAvBclBO5Q:ba3dc8f) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/Jenkinsfiles/Linux-xfs#L17)):*
> ```
> 	     /usr/bin/sudo /bin/cp /host/playpen/btrfs/* /sbin/
> 	     /usr/bin/sudo /bin/ln -s $(/bin/pwd) /oscar/betrfs
> 	     cp -r /usr/src/linux-source-3.11.10-ftfs /oscar/betrfs/linux-3.11.10
> ```

Is there a reason this is being copied? I don't think it's needed.
___
*[qemu-utils/xfstests/config, line 34 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5vttH4m1VrsSB8h8w:-MW5vttH4m1VrsSB8h8x:b-wlnfma) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/qemu-utils/xfstests/config#L34)):*
> ```
> ## DEP: Version as of roughly Apr '17.  Older versions don't
> ##      build properly with autoconf
> XFSTESTS_COMMIT=22ea2f8
> ```

Was rolling this forward intentional?
___
*[qemu-utils/xfstests/xfstests.sh, line 7 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5zQ9uCcMWDOGv8Xgi:-MW5zQ9uCcMWDOGv8Xgj:bvaiek1) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/qemu-utils/xfstests/xfstests.sh#L7)):*
> ```Shell
> 
> ## Check argument count
> if [ $# != 1 ] && [ $# != 2 ]; then
> ```

Remove this check.
___
*[qemu-utils/xfstests/xfstests.sh, line 14 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5zItL6rO5mhPu6E7k:-MW5zItL6rO5mhPu6E7l:b-7ropln) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/qemu-utils/xfstests/xfstests.sh#L14)):*
> ```Shell
> 
> ## Make sure the first argument is what is expected
> if [ $1 == "--force-hdd" ]; then
> ```

ditto
___
*[qemu-utils/xfstests/xfstests.sh, line 24 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5zm6j2T_Zrv5gEUdh:-MW5zm6j2T_Zrv5gEUdi:b-1t3bv6) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/qemu-utils/xfstests/xfstests.sh#L24)):*
> ```Shell
> 
> ## Set KERNEL_VERSION if there is a second argument
> if [[ $# -eq 2 ]]; then
> ```

Change to `[[ $# -eq 1 ]]` if check for --force-hdd and --force-ssd is removed.

**Review by msagarpatel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/20)* status: 17 of 19 files reviewed, 7 unresolved discussions (waiting on @donporter)

___
*[Jenkinsfiles/Linux-xfs, line 19 at r5](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW6LWWIBaIjLU36RgKV:-MW6LWWIBaIjLU36RgKW:b-5vxxo0) ([raw file](https://github.com/oscarlab/betrfs/blob/cae56a2079db1de15d91f02d603e8d971db097cf/Jenkinsfiles/Linux-xfs#L19)):*
> ```
> 	     cp -r /usr/src/linux-source-3.11.10-ftfs /oscar/betrfs/linux-3.11.10
> 	     cd /oscar/betrfs/qemu-utils/xfstests/
> 	     ./xfstests.sh --force-hdd
> ```

Just want to note that the parameter won't cause any problems, but it's not needed either.
___
*[qemu-utils/xfstests/xfstests.sh, line 24 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5zm6j2T_Zrv5gEUdh:-MW6L3wR4nekPjDX5Ssn:bdq4hqe) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/qemu-utils/xfstests/xfstests.sh#L24)):*
<details><summary><i>Previously, msagarpatel (Sagar Patel) wrote…</i></summary><blockquote>

Change to `[[ $# -eq 1 ]]` if check for --force-hdd and --force-ssd is removed.
</blockquote></details>

Actually, remove this altogether. About the recommendations above: we can keep these checks, but they're not really needed in this repo.

**Review by msagarpatel — COMMENTED** [review]
> Reviewed 2 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/20)* status: all files reviewed, 7 unresolved discussions (waiting on @donporter)

**Review by donporter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/20)* status: all files reviewed, 7 unresolved discussions (waiting on @msagarpatel)

___
*[benchmarks/clear-fs-caches.sh, line 36 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5tEfk9zKsHUiJ6Hfc:-MW6b2m23M_3onD0LViD:bga752f) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/benchmarks/clear-fs-caches.sh#L36)):*
<details><summary><i>Previously, msagarpatel (Sagar Patel) wrote…</i></summary><blockquote>

Is this necessary? module is defined in fs-info.sh, and that script is sourced by this script.
</blockquote></details>

Sort of.  It is more like useful debugging.  I hit a case where it was not set correctly, and it was not trivial to figure out why.  This line of debugging info seemed worth keeping for a clearer error, should a similar problem arise in the future.
___
*[filesystem/ftfs_module.c, line 78 at r5](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW6E3VU5ZSrZewnaahM:-MW6cQBh9XoJHSwjwM0r:b-qr4w56) ([raw file](https://github.com/oscarlab/betrfs/blob/fab3824cb1c33eeb7049ba08cbcaba6be16e657d/filesystem/ftfs_module.c#L78)):*
<details><summary><i>Previously, msagarpatel (Sagar Patel) wrote…</i></summary><blockquote>

Should all of these function declarations and definitions be removed as well?
</blockquote></details>

I don't understand this comment.  We definitely need a module exit function.  Perhaps placed in the wrong code?
___
*[Jenkinsfiles/Linux-xfs, line 13 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5ySXy-2bXZ1lH1TpQ:-MW6bcyLCsz5z1gWkPn_:b-896fix) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/Jenkinsfiles/Linux-xfs#L13)):*
<details><summary><i>Previously, msagarpatel (Sagar Patel) wrote…</i></summary><blockquote>

15 minutes should be sufficient.
</blockquote></details>

Done.
___
*[Jenkinsfiles/Linux-xfs, line 17 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5yKUW6VOAvBclBO5P:-MW6bnk-78DK3lsFxKVX:bq07gz5) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/Jenkinsfiles/Linux-xfs#L17)):*
<details><summary><i>Previously, msagarpatel (Sagar Patel) wrote…</i></summary><blockquote>

Is there a reason this is being copied? I don't think it's needed.
</blockquote></details>

The linux source is not in the public repo.
___
*[qemu-utils/xfstests/config, line 34 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5vttH4m1VrsSB8h8w:-MW6bx41AVTTJyvbtyzJ:bb77ufg) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/qemu-utils/xfstests/config#L34)):*
<details><summary><i>Previously, msagarpatel (Sagar Patel) wrote…</i></summary><blockquote>

Was rolling this forward intentional?
</blockquote></details>

Yes.
___
*[qemu-utils/xfstests/xfstests.sh, line 7 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5zQ9uCcMWDOGv8Xgi:-MW6cGlpAem_oCoUsA76:b-896fix) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/qemu-utils/xfstests/xfstests.sh#L7)):*
<details><summary><i>Previously, msagarpatel (Sagar Patel) wrote…</i></summary><blockquote>

Remove this check.
</blockquote></details>

Done.
___
*[qemu-utils/xfstests/xfstests.sh, line 14 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5zItL6rO5mhPu6E7k:-MW6cHQs8JbWOxRJNOjl:b-896fix) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/qemu-utils/xfstests/xfstests.sh#L14)):*
<details><summary><i>Previously, msagarpatel (Sagar Patel) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[qemu-utils/xfstests/xfstests.sh, line 24 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5zm6j2T_Zrv5gEUdh:-MW6cJ5x9jft4whl3XSY:b-896fix) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/qemu-utils/xfstests/xfstests.sh#L24)):*
<details><summary><i>Previously, msagarpatel (Sagar Patel) wrote…</i></summary><blockquote>

Actually, remove this altogether. About the recommendations above: we can keep these checks, but they're not really needed in this repo.
</blockquote></details>

Done.

**Review by donporter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/20)* status: 17 of 19 files reviewed, 7 unresolved discussions (waiting on @msagarpatel)

___
*[filesystem/ftfs_module.c, line 78 at r5](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW6E3VU5ZSrZewnaahM:-MW6cqimEZ3gvnRUfUUk:b94eytf) ([raw file](https://github.com/oscarlab/betrfs/blob/fab3824cb1c33eeb7049ba08cbcaba6be16e657d/filesystem/ftfs_module.c#L78)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

I don't understand this comment.  We definitely need a module exit function.  Perhaps placed in the wrong code?
</blockquote></details>

nm, I see.  Explanation: what is going on here is that we moved a bunch of this code into the unmount path, rather than module unload path.  The stuff that remains here really belongs here.

The code used to take some parameters at module load time that are really mountpoint-specific.  For xfstests, we migrated some of them (and initialization) to mount time.

**Review by msagarpatel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/20)* status: all files reviewed, 2 unresolved discussions (waiting on @donporter)

___
*[benchmarks/clear-fs-caches.sh, line 36 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5tEfk9zKsHUiJ6Hfc:-MW6d3Na-1sk1c-f5og_:b-7u4cf9) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/benchmarks/clear-fs-caches.sh#L36)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Sort of.  It is more like useful debugging.  I hit a case where it was not set correctly, and it was not trivial to figure out why.  This line of debugging info seemed worth keeping for a clearer error, should a similar problem arise in the future.
</blockquote></details>

Would it be better to use `set -u` in conjunction with `set -e`? `set -u` will:
- print an error message about a variable not being defined
- return non-zero error code.

The latter will cause the script to stop executing if used in conjunction with `set -e`.
___
*[filesystem/ftfs_module.c, line 78 at r5](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW6E3VU5ZSrZewnaahM:-MW6dc5OEMSrmouuo6zC:b-4fj2ea) ([raw file](https://github.com/oscarlab/betrfs/blob/fab3824cb1c33eeb7049ba08cbcaba6be16e657d/filesystem/ftfs_module.c#L78)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

nm, I see.  Explanation: what is going on here is that we moved a bunch of this code into the unmount path, rather than module unload path.  The stuff that remains here really belongs here.

The code used to take some parameters at module load time that are really mountpoint-specific.  For xfstests, we migrated some of them (and initialization) to mount time.
</blockquote></details>

My bad, I thought I retracted this comment. Thanks for the context of the changes though.
___
*[Jenkinsfiles/Linux-xfs, line 17 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5yKUW6VOAvBclBO5P:-MW6dqFi7iX_A-in0wZu:brnaqfs) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/Jenkinsfiles/Linux-xfs#L17)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

The linux source is not in the public repo.
</blockquote></details>

Yes, but the Jenkins jobs don't need the kernel tree. The Jenkins nodes' kernel is being mapped into the container. Refer to this parameter above: `-v /playpen/linux-source-3.11.10-ftfs:/usr/src/linux-source-3.11.10-ftfs`.
___
*[qemu-utils/xfstests/config, line 34 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5vttH4m1VrsSB8h8w:-MW6ef0b9jZVoQ9ZAKE5:b-2rnf0w) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/qemu-utils/xfstests/config#L34)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Resolved. Should we roll forward in the private repo?

**Review by donporter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/20)* status: all files reviewed, 2 unresolved discussions (waiting on @msagarpatel)

___
*[benchmarks/clear-fs-caches.sh, line 36 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5tEfk9zKsHUiJ6Hfc:-MW6hXoqEJQbLgn_JJ5y:b-lmp319) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/benchmarks/clear-fs-caches.sh#L36)):*
<details><summary><i>Previously, msagarpatel (Sagar Patel) wrote…</i></summary><blockquote>

Would it be better to use `set -u` in conjunction with `set -e`? `set -u` will:
- print an error message about a variable not being defined
- return non-zero error code.

The latter will cause the script to stop executing if used in conjunction with `set -e`.
</blockquote></details>

Yes!  Level up my bash!
___
*[Jenkinsfiles/Linux-xfs, line 17 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5yKUW6VOAvBclBO5P:-MW6hmG3Cf2Wk_7fkHpu:b86652v) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/Jenkinsfiles/Linux-xfs#L17)):*
<details><summary><i>Previously, msagarpatel (Sagar Patel) wrote…</i></summary><blockquote>

Yes, but the Jenkins jobs don't need the kernel tree. The Jenkins nodes' kernel is being mapped into the container. Refer to this parameter above: `-v /playpen/linux-source-3.11.10-ftfs:/usr/src/linux-source-3.11.10-ftfs`.
</blockquote></details>

Sure, let's try it.  
___
*[qemu-utils/xfstests/config, line 34 at r4](https://reviewable.io/reviews/oscarlab/betrfs/20#-MW5vttH4m1VrsSB8h8w:-MW6iO_72BMYi1EhMzW5:bo6189o) ([raw file](https://github.com/oscarlab/betrfs/blob/fcd3206ca83216a177f684cd4ceb3d660babf2cc/qemu-utils/xfstests/config#L34)):*
<details><summary><i>Previously, msagarpatel (Sagar Patel) wrote…</i></summary><blockquote>

Resolved. Should we roll forward in the private repo?
</blockquote></details>

We are rolling forward to match private.

**Review by msagarpatel — DISMISSED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @donporter)

**Review by msagarpatel — APPROVED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @donporter)

**Comment by donporter** [comment]
Retest Benchmarks please.  Timeout - may need to bump it up

**Comment by donporter** [comment]
Retest Toku please.  Also a timeout.  May need to increase from enabling concurrent workers.

**Pull request merged**
