### PR TITLE
Update Jenkinsfile to work with leeroy2

### PR DESCRIPTION
**Pull request by dcowhig**
Jenkins no longer calls VM directly
Changes from private repo merged

### CODE REVIEW

**Comment by dcowhig** [comment]
This is failing due to https://issues.jenkins-ci.org/browse/JENKINS-43977

.gitmodules points to this dead URL (at least as of a few minutes ago):

https://git.tukaani.org/xz.git/

**Comment by donporter** [comment]
I was able to clone this repo just now.  I cannot browse the url per se, though.

**Comment by wenhuizhang** [comment]
Open source community usually use Nexus Repository (https://www.sonatype.com/nexus-repository-sonatype) to host all binaries and libraries as a **Jenkins Master** . Probably clone from uncontrolled sources with controlled versions is dangerous sometimes.

**Comment by dcowhig** [comment]
Retest this please

**Pull request merged**
