### PR TITLE
unlink failed because test.file did not exist. as a proof

### PR DESCRIPTION
**Pull request by Jun-Yuan**
unlink failed because test.file did not exist.

Why do we have cases the pre-test file not created and unlink
fails on it?

re-enabled the patch of node size

---
This change is [Reviewable](https://reviewable.io/reviews/oscarlab/betrfs/12)

### CODE REVIEW

**Comment by dcowhig** [comment]
Jenkins, restest this please. 

Had to reboot the Jenkins node...

**Comment by Jun-Yuan** [comment]
ok. it still failed. I am scratching my head as it is not reproduced on my vm box. Is it possible for us to get the dmesg log of the crashed workgroup#1?

**Comment by ericafu1122** [comment]
retest this please

**Comment by ericafu1122** [comment]
retest this please

**Comment by ericafu1122** [comment]
retest this please

**Pull request merged**
